package com.unu.sistemadegestiondocumentaria.ui.raven.form;

import com.unu.sistemadegestiondocumentaria.ui.raven.tabbed.TabbedForm;
import com.unu.sistemadegestiondocumentaria.ui.raven.tabbed.WindowsTabbed;
import javax.swing.JOptionPane;
import raven.alerts.MessageAlerts;
import raven.popup.component.PopupCallbackAction;
import raven.popup.component.PopupController;
import raven.toast.Notifications;

/**
 *
 * @author RAVEN
 */
public class FormOficios extends TabbedForm {

    private boolean esAgregar = true;

    /**
     * Creates new form TestForm
     */
    public FormOficios(boolean esAgregar) {
        this.esAgregar = esAgregar;
        initComponents(); 
        String label = (this.esAgregar) ? "EsAgregar" : "EsEditar";
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlFondo = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(830, 504));
        setLayout(null);

        pnlFondo.setPreferredSize(new java.awt.Dimension(830, 504));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        add(pnlFondo);
        pnlFondo.setBounds(0, 0, 830, 504);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean formClose() {
//        if (txt.getText().trim().equals("")) {
            return true;
//        }
//        int opt = JOptionPane.showConfirmDialog(this, "¿Estás seguro de salir sin guardar correctamente los datos?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
//        return opt == JOptionPane.YES_OPTION;
    }

    @Override
    public void formOpen() {
//        System.out.println("Form open");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
