package com.unu.sistemadegestiondocumentaria.ui.raven.form;

import com.unu.sistemadegestiondocumentaria.ui.raven.tabbed.TabbedForm;
import com.unu.sistemadegestiondocumentaria.ui.raven.tabbed.WindowsTabbed;
import javax.swing.JOptionPane;
import raven.alerts.MessageAlerts;
import raven.popup.component.PopupCallbackAction;
import raven.popup.component.PopupController;
import raven.toast.Notifications;

/**
 *
 * @author RAVEN
 */
public class FormOficios1 extends TabbedForm {

    private boolean esAgregar = true;

    /**
     * Creates new form TestForm
     */
    public FormOficios1(boolean esAgregar) {
        this.esAgregar = esAgregar;
        initComponents(); 
        String label = (this.esAgregar) ? "EsAgregar" : "EsEditar";
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(830, 504));
        setLayout(null);

        jLabel1.setText("Expediente: ");
        add(jLabel1);
        jLabel1.setBounds(14, 14, 63, 21);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(89, 9, 76, 26);

        jLabel2.setText("Sustentación:");
        add(jLabel2);
        jLabel2.setBounds(211, 14, 71, 21);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(294, 9, 280, 26);

        jLabel3.setText("Alumno: ");
        add(jLabel3);
        jLabel3.setBounds(14, 41, 49, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hola, soy un alumno");
        add(jLabel4);
        jLabel4.setBounds(89, 41, 450, 16);

        jLabel5.setText("Fecha: ");
        add(jLabel5);
        jLabel5.setBounds(14, 100, 37, 26);

        jTextField1.setText("jTextField1");
        add(jTextField1);
        jTextField1.setBounds(90, 100, 222, 26);

        jLabel6.setText("Destinatarios: ");
        add(jLabel6);
        jLabel6.setBounds(600, 50, 74, 16);

        jRadioButton1.setText("Expediente");
        add(jRadioButton1);
        jRadioButton1.setBounds(601, 12, 82, 21);

        jRadioButton2.setText("Sustentación");
        add(jRadioButton2);
        jRadioButton2.setBounds(701, 12, 93, 21);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nro", "Documento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(610, 340, 198, 139);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 320, 238, 90);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        add(jScrollPane3);
        jScrollPane3.setBounds(320, 320, 238, 90);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Asunto");
        jLabel7.setToolTipText("");
        add(jLabel7);
        jLabel7.setBounds(30, 280, 230, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Referencia");
        add(jLabel8);
        jLabel8.setBounds(320, 280, 240, 16);

        jButton1.setText("AGREGAR");
        add(jButton1);
        jButton1.setBounds(200, 440, 180, 27);

        jButton2.setText("Agregar");
        add(jButton2);
        jButton2.setBounds(600, 250, 76, 27);

        jButton3.setText("Eliminar");
        add(jButton3);
        jButton3.setBounds(710, 250, 79, 27);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3);
        jComboBox3.setBounds(600, 70, 190, 26);

        jLabel9.setText("Documentos del Expediente");
        add(jLabel9);
        jLabel9.setBounds(610, 310, 180, 16);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Destinatario", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(30);
            jTable2.getColumnModel().getColumn(2).setHeaderValue("");
        }

        add(jScrollPane4);
        jScrollPane4.setBounds(600, 100, 198, 139);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox4);
        jComboBox4.setBounds(90, 140, 330, 26);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox5);
        jComboBox5.setBounds(90, 180, 330, 26);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox6);
        jComboBox6.setBounds(90, 220, 330, 26);

        jLabel10.setText("Destinatario: ");
        add(jLabel10);
        jLabel10.setBounds(10, 220, 70, 20);

        jLabel11.setText("Presidente: ");
        add(jLabel11);
        jLabel11.setBounds(14, 141, 70, 20);

        jLabel12.setText("Destinatario: ");
        add(jLabel12);
        jLabel12.setBounds(10, 180, 70, 20);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean formClose() {
//        if (txt.getText().trim().equals("")) {
            return true;
//        }
//        int opt = JOptionPane.showConfirmDialog(this, "¿Estás seguro de salir sin guardar correctamente los datos?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
//        return opt == JOptionPane.YES_OPTION;
    }

    @Override
    public void formOpen() {
//        System.out.println("Form open");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
